In [1]:
import pandas as pd
array = [
    {'tit': 'polarity', 'clas': ['bom', 'mau'], 'testes': [['guerra', 'mau'], [
        'pizza', 'bom'], ['descançar', 'bom'], ['cansado', 'mau']]},
    {'tit': 'class-animais', 'clas': ['ave', 'mamífero', 'peixe'], 'testes': [['melro', 'ave'], ['águia', 'ave'], ['pomba', 'ave'], ['gato', 'mamífero'], ['leão', 'mamífero'], ['macaco', 'mamífero'], ['boi', 'mamífero'], ['tubarão', 'peixe'], ['sardinha', 'peixe'], ['salmão', 'peixe']]}]

words = ['bom', 'mau', 'ave', 'mamífero', 'peixe'] # placeholder
example_missing_words = ['bom', 'ave', 'mamífero', 'peixe']  # placeholder
dataframe = pd.DataFrame(array)
dataframe

,tit,clas,testes
0,polarity,"[bom, mau]","[[guerra, mau], [pizza, bom], [descançar, bom]..."
1,class-animais,"[ave, mamífero, peixe]","[[melro, ave], [águia, ave], [pomba, ave], [ga..."

In [2]:
# Utils
# Não testei com as funções do modelo mas presumo que de logo

def _remove_non_existing_words(row):
    return all([clas in words for clas in row['clas']])
    # return all([clas in model.wv.key_to_index for clas in classes]) Usar isto

import random # Remover quando remover o return random
random.seed(42)  # Remover quando remover o return random

def _similarity(row):
    # return model.wv.similarity(row['word'], row['testes']) Usar isto
    return random.random()

In [3]:
# Unknown_words
all_words = dataframe["clas"].explode()
unknown_words = all_words[~all_words.isin(example_missing_words)] # O ~ nega o dataframe (~[True, False, True] -> [False, True, False])
unknown_words

0    mau
Name: clas, dtype: object

In [4]:
# Remove rows with words not present in the dictionary
dataframe[dataframe.apply(_remove_non_existing_words, axis=1)]
dataframe

,tit,clas,testes
0,polarity,"[bom, mau]","[[guerra, mau], [pizza, bom], [descançar, bom]..."
1,class-animais,"[ave, mamífero, peixe]","[[melro, ave], [águia, ave], [pomba, ave], [ga..."

In [5]:
# Dividir Testes em várias linhas
dataframe = dataframe.explode('testes')  
dataframe

             tit                    clas              testes
0       polarity              [bom, mau]       [guerra, mau]
0       polarity              [bom, mau]        [pizza, bom]
0       polarity              [bom, mau]    [descançar, bom]
0       polarity              [bom, mau]      [cansado, mau]
1  class-animais  [ave, mamífero, peixe]        [melro, ave]
1  class-animais  [ave, mamífero, peixe]        [águia, ave]
1  class-animais  [ave, mamífero, peixe]        [pomba, ave]
1  class-animais  [ave, mamífero, peixe]    [gato, mamífero]
1  class-animais  [ave, mamífero, peixe]    [leão, mamífero]
1  class-animais  [ave, mamífero, peixe]  [macaco, mamífero]
1  class-animais  [ave, mamífero, peixe]     [boi, mamífero]
1  class-animais  [ave, mamífero, peixe]    [tubarão, peixe]
1  class-animais  [ave, mamífero, peixe]   [sardinha, peixe]
1  class-animais  [ave, mamífero, peixe]     [salmão, peixe]

In [6]:
# Dividir testes em duas colunas
dataframe[['word', 'answer']] = pd.DataFrame(
    dataframe['testes'].tolist(), index=dataframe.index)
dataframe

,tit,clas,testes,word,answer
0,polarity,"[bom, mau]","[guerra, mau]",guerra,mau
0,polarity,"[bom, mau]","[pizza, bom]",pizza,bom
0,polarity,"[bom, mau]","[descançar, bom]",descançar,bom
0,polarity,"[bom, mau]","[cansado, mau]",cansado,mau
1,class-animais,"[ave, mamífero, peixe]","[melro, ave]",melro,ave
1,class-animais,"[ave, mamífero, peixe]","[águia, ave]",águia,ave
1,class-animais,"[ave, mamífero, peixe]","[pomba, ave]",pomba,ave
1,class-animais,"[ave, mamífero, peixe]","[gato, mamífero]",gato,mamífero
1,class-animais,"[ave, mamífero, peixe]","[leão, mamífero]",leão,mamífero
1,class-animais,"[ave, mamífero, peixe]","[macaco, mamífero]",macaco,mamífero
1,class-animais,"[ave, mamífero, peixe]","[boi, mamífero]",boi,mamífero
1,class-animais,"[ave, mamífero, peixe]","[tubarão, peixe]",tubarão,peixe
1,class-animais,"[ave, mamífero, peixe]","[sardinha, peixe]",sardinha,peixe
1,class-animais,"[ave, mamífero, peixe]","[salmão, peixe]",salmão,peixe

In [7]:
# Dividir classes em várias linhas
dataframe = dataframe.explode('clas')
dataframe[:10]

             tit      clas            testes       word answer
0       polarity       bom     [guerra, mau]     guerra    mau
0       polarity       mau     [guerra, mau]     guerra    mau
0       polarity       bom      [pizza, bom]      pizza    bom
0       polarity       mau      [pizza, bom]      pizza    bom
0       polarity       bom  [descançar, bom]  descançar    bom
0       polarity       mau  [descançar, bom]  descançar    bom
0       polarity       bom    [cansado, mau]    cansado    mau
0       polarity       mau    [cansado, mau]    cansado    mau
1  class-animais       ave      [melro, ave]      melro    ave
1  class-animais  mamífero      [melro, ave]      melro    ave

In [8]:
# predict do modelo
dataframe['predicted'] = dataframe.apply(_similarity, axis=1)
dataframe[:10]

             tit      clas            testes       word answer  predicted
0       polarity       bom     [guerra, mau]     guerra    mau   0.639427
0       polarity       mau     [guerra, mau]     guerra    mau   0.025011
0       polarity       bom      [pizza, bom]      pizza    bom   0.275029
0       polarity       mau      [pizza, bom]      pizza    bom   0.223211
0       polarity       bom  [descançar, bom]  descançar    bom   0.736471
0       polarity       mau  [descançar, bom]  descançar    bom   0.676699
0       polarity       bom    [cansado, mau]    cansado    mau   0.892180
0       polarity       mau    [cansado, mau]    cansado    mau   0.086939
1  class-animais       ave      [melro, ave]      melro    ave   0.421922
1  class-animais  mamífero      [melro, ave]      melro    ave   0.029797

In [12]:
# Buscar maior predicted
result = dataframe.groupby(by=['word']).max()
result

                     tit   clas              testes    answer  predicted
word
boi        class-animais  peixe     [boi, mamífero]  mamífero   0.847494
cansado         polarity    mau      [cansado, mau]       mau   0.892180
descançar       polarity    mau    [descançar, bom]       bom   0.736471
gato       class-animais  peixe    [gato, mamífero]  mamífero   0.809430
guerra          polarity    mau       [guerra, mau]       mau   0.639427
leão       class-animais  peixe    [leão, mamífero]  mamífero   0.805819
macaco     class-animais  peixe  [macaco, mamífero]  mamífero   0.957213
melro      class-animais  peixe        [melro, ave]       ave   0.421922
pizza           polarity    mau        [pizza, bom]       bom   0.275029
pomba      class-animais  peixe        [pomba, ave]       ave   0.649884
salmão     class-animais  peixe     [salmão, peixe]     peixe   0.829405
sardinha   class-animais  peixe   [sardinha, peixe]     peixe   0.973116
tubarão    class-animais  peixe    [tubarão, peixe]     peixe   0.807128
águia      class-animais  peixe        [águia, ave]       ave   0.505355

In [15]:
(result['clas'] == result['answer']).value_counts()

False    9
True     5
dtype: int64

In [16]:
result[result['clas'] == result['answer']]

                    tit   clas             testes answer  predicted
word
cansado        polarity    mau     [cansado, mau]    mau   0.892180
guerra         polarity    mau      [guerra, mau]    mau   0.639427
salmão    class-animais  peixe    [salmão, peixe]  peixe   0.829405
sardinha  class-animais  peixe  [sardinha, peixe]  peixe   0.973116
tubarão   class-animais  peixe   [tubarão, peixe]  peixe   0.807128